# PATHs
export PATH="${PATH}:${HOME}/bin:${HOME}/go/bin"

# Default to nvim editor
export EDITOR="nvim"

# My own terminal habits
alias habits='history | sed "s/^[[:space:]]*[0-9]*[[:space:]]*//" | sort | uniq -c | sort -n -r | head -n 20'

# Shortcut to reset
alias c='clear && reset && tmux clear-history'

# Git aliases with completion
source /usr/share/bash-completion/completions/git
__git_shortcut () {
  local _alias="${1}"
  shift 1
  local args="$@"
  alias "${_alias}"="git ${args}"
  __git_complete "${_alias}" "_git_${1}"
}
__git_shortcut ga add
__git_shortcut gap add -p
__git_shortcut gc commit -m
__git_shortcut gcA commit --amend -m
__git_shortcut gca commit --amend -C HEAD
__git_shortcut gci commit -v
__git_shortcut gco checkout
__git_shortcut gd diff
__git_shortcut gdc diff --cached
__git_shortcut gl log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)%Creset' --abbrev-commit
__git_shortcut gp push
__git_shortcut gpl pull
__git_shortcut gplr pull '--rebase'
__git_shortcut gr reset
__git_shortcut gs status

# Tokens, like for GitHub
for token in ${HOME}/.tokens/*; do
  export $(basename "${token}")="$(cat "${token}")"
done

# `cdp` and `cdpo` aliases with completion
_cd_projects() {
  local basepath="${HOME}/projects"
  if [[ $1 = 'cdpo' ]]; then
    basepath="${basepath}/oss"
  fi

  pushd $basepath > /dev/null
    _cd
  popd > /dev/null

  count=${#COMPREPLY[@]}
  index=0
  while [ "$index" -lt "$count" ]; do
    COMPREPLY[$index]="${COMPREPLY[$index]}/"
    let "index++"
  done
}
function cdp()  { cd $HOME/projects/$@; }
function cdpo() { cd $HOME/projects/oss/$@; }
complete -F _cd_projects -o nospace cdpo
complete -F _cd_projects -o nospace cdp

if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
  GIT_PROMPT_ONLY_IN_REPO=1
  source $HOME/.bash-git-prompt/gitprompt.sh
fi
